name: "9.2.1"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal_9-2-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/73ad5f9e147c0d2a2061f1d4bd91e05078dc0b58.tar.gz

      - name: Compile
        run: |
          nix-shell nix/ghc_9-2-1.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always"

      - name: DocTest
        run: |
          nix-shell nix/ghc_9-2-1.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always && \
             RUN_DOCTEST=true cabal test doctest --test-show-details=direct"

      - name: Property Tests
        run: |
          nix-shell nix/ghc_9-2-1.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always && \
             MAX_RUNS=100000 cabal test props --test-show-details=direct"
